### PR TITLE
[WPEBackend-rdk] Fixed cmake package find scripts for libinput, libud…

### PR DESCRIPTION
**Pull request by renebarto**
…ev and libxkbcommon. They now actually look for the headers and libraries needed.

### CODE REVIEW

**Comment by zdobersek** [comment]
LGTM.

**Comment by blino** [comment]
Why is this needed?
Isn't pkg-config already returning the proper paths?

**Comment by renebarto** [comment]
Oliver, no, not if you build out of tree, as only the library name is used, not the path.

 
Groeten / Kind regards,
 
René Barto

**Comment by blino** [comment]
Even when using `PKG_CONFIG_SYSROOT_DIR` to point to your staging dir?

**Comment by renebarto** [comment]
That is only used for host builds, not target builds afaik

 
Groeten / Kind regards,
 
René Barto

**Pull request merged**
