### PR TITLE
[cmake] add EGL package's CFlags

### PR DESCRIPTION
**Pull request by moorthy-bs**
Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>

### CODE REVIEW

**Comment by moorthy-bs** [comment]
Is there anything to address on this PR?

**Comment by wouterlucas** [comment]
Although I don't see any harm with this change, can you provide a little more context of what you're fixing  / changing here?

I've recently added a similar change to the bcm-nexus backend, I guess this is the "one size fits all" solution to that.

**Comment by moorthy-bs** [comment]
> Although I don't see any harm with this change, can you provide a little more context of what you're fixing / changing here?
> 
> I've recently added a similar change to the bcm-nexus backend, I guess this is the "one size fits all" solution to that.

NXP's i.MX8MQ EVK platform's EGL provider (imx-gpu-viv) defines some macros (-DLINUX -DEGL_API_FB -DWL_EGL_PLATFORM) in its egl.pc which are required to determine the right EGLNativeDisplayType in eglplatform.h otherwise it goes for default option (x11) and includes unavailable x11 header files that tends to fatal error. 
As a generic solution, added definitions in EGL_CFLAGS through pkg config.

**Comment by wouterlucas** [comment]
Thanks for the details @moorthy-bs ! 

LGTM

**Pull request merged**
