### PR TITLE
Adapt to WPEBackend -> libwpe change and increase version to libwpe-0.2

### PR DESCRIPTION
**Pull request by woutervanh**
WPEBackend changed name to libwpe, current version is 1.0.0
However, internally (pkg-conf) version has API-version, which is 0.2.

### CODE REVIEW

**Comment by woutervanh** [comment]
It's not so conveniant what to use by now. There's also the stable and unstable webkit, so I suppose we need to keep up with the stable version here?

**Comment by aperezdc** [comment]
This is definitely interesting, IMHO it would be great to support the new API. This is a good initial step, but there are a few more changes needed to better adapt to version 0.2 of the API:

- The `wpe_key_mapper_interface` has been removed, and now there is a keymap API based on `libxkbcommon` (https://github.com/WebPlatformForEmbedded/libwpe/pull/24 and https://github.com/WebPlatformForEmbedded/libwpe/pull/23).

- Now it's possible to indicate active keyboard modifiers in pointer events (https://github.com/WebPlatformForEmbedded/libwpe/pull/22).

@woutervanh Would you be willing to look into the above and improve the PR?

**Comment by aperezdc** [comment]
There's also support for checking the version of `WPEBackend`/`libwpe` at build time using the `WPE_BACKEND_CHECK_VERSION()` macro. That was merged in https://github.com/WebPlatformForEmbedded/libwpe/pull/19 and available since WPEBackend 0.2.0 — if the `WPE_BACKEND_CHECK_VERSION` is undefined, then WPEBackend 0.1.0 is being used.

**Comment by woutervanh** [comment]
> This is definitely interesting, IMHO it would be great to support the new API. This is a good initial step, but there are a few more changes needed to better adapt to version 0.2 of the API:
> 
> * The `wpe_key_mapper_interface` has been removed, and now there is a keymap API based on `libxkbcommon` ([WebPlatformForEmbedded/libwpe#24](https://github.com/WebPlatformForEmbedded/libwpe/pull/24) and [WebPlatformForEmbedded/libwpe#23](https://github.com/WebPlatformForEmbedded/libwpe/pull/23)).
> * Now it's possible to indicate active keyboard modifiers in pointer events ([WebPlatformForEmbedded/libwpe#22](https://github.com/WebPlatformForEmbedded/libwpe/pull/22)).
> 
> @woutervanh Would you be willing to look into the above and improve the PR?

Isn't that something which was already addressed? The comment on commit [https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/commit/52000105bfa96f9f672e7410599cc70a221f7e82](url) is exactly what you mention:

>Input: Update to new WPEBackend API
>
>WPEBackend now requires libxkbcommon and includes API to handle XKB
>contexts. The keymapper interface has been removed, and the code moved
>to WebKit, so that backends don't need to implement it anymore.

**Comment by aperezdc** [comment]
@woutervanh You are right, no need to go over the input handling — which means that currently `master` does not really work with WPEBackend≤0.2.0 either!

The backend is only missing the changes you proposed in this PR after all to work with `libwpe` 1.0.0, so I think we should merge this.

**Comment by aperezdc** [comment]
There has been no negative comments, so let's merge this!

**Pull request merged**
