### PR TITLE
single-headers and API version

### PR DESCRIPTION
**Pull request by psaavedra**
* Enforce single-header includes
* FindWPE: use API version for pkg-config file, library name

Still WIP: Pending of tests: compile, yocto, execution.

### CODE REVIEW

**Comment by psaavedra** [comment]
This code is being tested against

**Comment by clopez** [comment]
The patch looks ok, but i think it lacks fixing the includes of the headers on more files.

I was not aware of this PR, and I happened to submit an alternative one in https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/pull/23
Sorry for duplicating work

**Comment by psaavedra** [comment]
This new revision of the PR:

    * FindWPE: use API version for pkg-config file, library name
    * Enforce single-header includes
      * wpe/wpe.h should be included instead of wpe/input.h, wpe/loader.h,
        wpe/pasteboard.h, wpe/renderer-host.h and wpe/view-backend.h
      * wpe/wpe-egl.h should be included instead of
        wpe/renderer-backend-egl.h
    
    This commit is equivalent to PR 23 [1] from clopez branch
    
    [1] https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/pull/23

**Comment by psaavedra** [comment]
Note: Not sure about the motivation of keep this up to date: https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/pull/22/files#diff-e93f5707e04b4dffaad039713e6ea02fL29

**Comment by clopez** [comment]
This still misses an include in src/wayland-egl/interfaces.h

Also, if you are updating it again instead of referring in the commit log to the #23 PR (that i will be happy to close as duplicated) please refer to the commit IDs from wpebackend that are relevant to this fix like i did on the commit logs from #23 PR

**Comment by aperezdc** [comment]
This is not needed anymore, and `master` currently is building fine against libwpe 1.0.0 — so let's just close the PR.

**Pull request closed without merging**
