### PR TITLE
XKBkeysym handling is modified for linux keycode greater than 255

### PR DESCRIPTION
**Pull request by nambirajang**
Signed-off-by: nrajang <nambirajan.g@lnttechservices.com>

### CODE REVIEW

**Comment by nambirajang** [comment]
@blino , Can you please review this change related to color key handling.

**Comment by blino** [comment]
xkbcommon does support keycodes > 255, we are using it precisely for the keycodes you have in your changelist (Red = 398, and so on...).

The proper solution is to add them to xkeyboard-config-2.7/keycodes/evdev

**Comment by blino** [comment]
Below is a subset of the xkeyboard-config patch we have.
Since there is common interest on this, we can try to submit this upstream.

```
--- xkeyboard-config-2.7.old/keycodes/evdev	2012-01-20 00:21:06.000000000 +0100
+++ xkeyboard-config-2.7/keycodes/evdev	2013-01-04 02:37:33.208685256 +0100
@@ -2,7 +2,7 @@
 
 default xkb_keycodes "evdev" {
 	minimum = 8;
-	maximum = 255;
+	maximum = 409;
 
         # Added for pc105 compatibility
         <LSGT> = 94;
@@ -290,6 +290,11 @@
 	<SUPR> =   206;
 	<HYPR> =   207;
 
+    <Red>         = 406;
+    <Green>       = 407;
+    <Yellow>      = 408;
+    <Blue>        = 409;
+
 	indicator 1  = "Caps Lock";
 	indicator 2  = "Num Lock";
 	indicator 3  = "Scroll Lock";
diff -ru xkeyboard-config-2.7.old/symbols/inet xkeyboard-config-2.7/symbols/inet
--- xkeyboard-config-2.7.old/symbols/inet	2012-01-20 00:21:06.000000000 +0100
+++ xkeyboard-config-2.7/symbols/inet	2013-01-04 02:39:26.762871203 +0100
@@ -225,6 +225,11 @@
     key <FK16>   {      [ XF86Launch7       ]       };
     key <FK17>   {      [ XF86Launch8       ]       };
     key <FK18>   {      [ XF86Launch9       ]       };
+
+    key <Red>    {      [ XF86Red           ]       };
+    key <Green>  {      [ XF86Green         ]       };
+    key <Yellow> {      [ XF86Yellow        ]       };
+    key <Blue>   {      [ XF86Blue          ]       };
 };
 
```

**Comment by nambirajang** [comment]
Hi Blino, 
We applied your changes and it is working good. 
But we need some modification in key code value assignment to meet our requirement.
Our App is expecting the below,

 XKB_KEY_XF86Yellow= VK_HAVI_COLORED_KEY_0;
XKB_KEY_XF86Blue=VK_HAVI_COLORED_KEY_1;
 XKB_KEY_XF86Red = VK_HAVI_COLORED_KEY_2;
 XKB_KEY_XF86Green= VK_HAVI_COLORED_KEY_3;

Can we make these changes in input-libxkbcommon.cpp file.

**Comment by blino** [comment]
This is already the case here:
https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/blob/master/src/input/XKB/input-libxkbcommon.cpp#L608

**Pull request merged**
